### ISSUE TITLE
setAlpha / getOpacity

### ISSUE THREAD

**Issue by chteuchteu** [code-mc/material-icon-lib#12]
`setAlpha` and `getOpacity` methods can be misleading.

Alpha is usually an integer between 0-255 (as it is for `setAlpha`), while opacity is a float from 0 to 1. What value do we retrieve when we call `getOpacity`?

I think you should create a `getAlpha` method and set `getOpacity` as deprecated for better understanding on this point.

Awesome project though!

**Comment by code-mc** [comment]
Ok so just to give some closure about this (I know this was issued months ago): the Drawable abstract class includes a bunch of methods, 2 of those are "setAlpha" and "getOpacity" which respectively take an integer and return an integer. I agree it is confusing, but it would be even more confusing to use different methods as then the original + new methods would be available to users (because they are inherited anyways from the abstract class)

Anyways, hope it is useful somehow even months after the question. Just trying to clean up some issues :D

**Comment by chteuchteu** [comment]
> Anyways, hope it is useful somehow even months after the question

Yes it is, thank you! Didn't knew these methods came from the Drawable class. Thanks for the answer!
